package com.cityapp.mvcdemo.IDao;

import com.cityapp.mvcdemo.domain.countrylanguage;
import com.cityapp.mvcdemo.domain.countrylanguageKey;

public interface countrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(countrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int insert(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int insertSelective(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    countrylanguage selectByPrimaryKey(countrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(countrylanguage record);
}